#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Prune all docker stuff
#?? 1.0.0
##?
##? Usage:
##?   prune
docs::parse "$@"

docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)