#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Prune all docker stuff
#?? 1.0.0
##?
##? Usage:
##?   prune
docs::parse "$@"

containers=$(docker ps -aq)
if [[ -z $containers ]]; then
  echo "ERROR: No cointainers to down"
  exit 1
fi

output::header "Stoping containers"
docker stop $containers

output::header "Removing containers"
docker rm $containers
