#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Prune all docker stuff
#?? 1.0.0
##?
##? Usage:
##?   prune
docs::parse "$@"

containers=$(docker ps -aq)

output::header "Stoping containers"
if [[ -n $containers ]]; then
  docker stop $containers
else
  echo "INFO: No containers to stop"
fi

output::header "Pruning"
yes | docker system prune -a