#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Make hexagonal structure for current DDD module
#?? 1.0.0
##?
##? Usage:
##?   ddd hexagonal <path>
docs::parse "$@"

mkdir -p "$path/application"
mkdir -p "$path/domain"
mkdir -p "$path/infrastructure"

echo "😬 Dooone!"
